version: '3.8'
services:
  api:
    build:
      context: ./backend
      dockerfile: api/Dockerfile
    container_name: hydrostat_api
    ports:
      - 8000:8000
    volumes:
    - type: bind
      source: ./backend/api/app
      target: /app
    - type: bind
      source: ./backend/.env
      target: /app/.env
    - type: bind
      source: ./backend/db/models.py
      target: /app/models.py
    command: ["fastapi", "run", "main.py", "--port", "8000", "--reload"]
    restart: on-failure
    depends_on:
      - database
  database:
    image: postgres:16.3-alpine
    container_name: hydrostat_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5433
    ports:
      - 5433:5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  webui:
    build:
      context: ./webui
      dockerfile: Dockerfile
    container_name: hydrostat_webui
    ports:
      - 5173:5173
    volumes:
      - ./webui:/app
      - ./webui/node_modules:/app/node_modules
    depends_on:
      - api

volumes:
  postgres_data: